#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf8e0;
constexpr uint24_t FX_DATA_BYTES = 462799;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t Cards_Bottom = 0x018810;
  constexpr uint24_t Cards_Bottom_Grey = 0x01CDAE;
  constexpr uint24_t Cards_Left = 0x02134C;
  constexpr uint24_t Cards_Right = 0x026C40;
  constexpr uint24_t Hand_Left = 0x02C534;
  constexpr uint24_t Hand_Right = 0x02C950;
  constexpr uint24_t Hand_Top = 0x02CD6C;
  constexpr uint24_t Suit = 0x02D0F5;
  constexpr uint24_t HUD_Top = 0x02D247;
  constexpr uint24_t HUD_Bottom = 0x02E161;
  constexpr uint24_t Numbers_3x5 = 0x02F807;
  constexpr uint24_t HUD_Trick_Score = 0x0325BD;
  constexpr uint24_t HUD_Game_Score = 0x032778;
  constexpr uint24_t Hand_Full = 0x03484A;
  constexpr uint24_t Hand_Full_Grey = 0x0348E5;
  constexpr uint24_t Rotate = 0x034980;
  constexpr uint24_t Flip = 0x03AEC2;
  constexpr uint24_t Bid_Round1 = 0x03C0C4;
  constexpr uint24_t Bid_Round2 = 0x03C828;
  constexpr uint24_t Bid_Suits = 0x03E32A;
  constexpr uint24_t Delay = 0x03E404;
  constexpr uint24_t Bid_Top = 0x03E95E;
  constexpr uint24_t Bid_Bottom = 0x03EAFE;
  constexpr uint24_t Bid_Left = 0x03EC9E;
  constexpr uint24_t Bid_Right = 0x03EE1A;
  constexpr uint24_t Bid_Top_Discard = 0x03EF96;
  constexpr uint24_t Bid_Bottom_Discard = 0x03F03A;
  constexpr uint24_t Bid_Left_Discard = 0x03F0DE;
  constexpr uint24_t Bid_Right_Discard = 0x03F188;
  constexpr uint24_t TitleEuchre = 0x03F232;
  constexpr uint24_t TitleEuchre_Assist = 0x057234;
  constexpr uint24_t TitleEuchre_Assist_Cursor = 0x058A36;
  constexpr uint24_t Dealer = 0x058B10;
  constexpr uint24_t EveryonePassed = 0x058B30;
  constexpr uint24_t KittyInstructions = 0x058C10;
  constexpr uint24_t PPOT = 0x058E49;
  constexpr uint24_t You_Won = 0x05BE4B;
  constexpr uint24_t You_Lost = 0x06670D;
}

