#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf850;
constexpr uint24_t FX_DATA_BYTES = 499520;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t Cards_Bottom = 0x018810;
  constexpr uint24_t Cards_Bottom_Grey = 0x01CDAE;
  constexpr uint24_t Cards_Left = 0x02134C;
  constexpr uint24_t Cards_Right = 0x026C40;
  constexpr uint24_t Hand_Left = 0x02C534;
  constexpr uint24_t Hand_Right = 0x02CBA8;
  constexpr uint24_t Hand_Top = 0x02D21C;
  constexpr uint24_t Suit = 0x02DD34;
  constexpr uint24_t PPOT = 0x02DE86;
  constexpr uint24_t Sound_Volume_Grey = 0x030E88;
  constexpr uint24_t Sound_Volume_White = 0x0316CA;
  constexpr uint24_t Sound_Checkbox = 0x031F0C;
  constexpr uint24_t Title = 0x031F1A;
  constexpr uint24_t HUD_Top = 0x03629C;
  constexpr uint24_t HUD_Bottom = 0x0371B6;
  constexpr uint24_t Score_Numbers_Bottom = 0x03885C;
  constexpr uint24_t Score_Numbers_Left = 0x03895A;
  constexpr uint24_t Score_Numbers_Right = 0x038A58;
  constexpr uint24_t Bid = 0x038B56;
  constexpr uint24_t Numbers_3x5 = 0x039524;
  constexpr uint24_t HighScores = 0x03C2DA;
  constexpr uint24_t HUD_Trick_Score = 0x03CCCC;
  constexpr uint24_t HUD_Game_Score = 0x03CE87;
  constexpr uint24_t Hand_Full = 0x03EF59;
  constexpr uint24_t Hand_Full_Grey = 0x03EFF4;
  constexpr uint24_t Rotate = 0x03F08F;
  constexpr uint24_t Flip = 0x0455D1;
  constexpr uint24_t Bid_Round1 = 0x0467D3;
  constexpr uint24_t Bid_Round2 = 0x046F37;
  constexpr uint24_t Bid_Suits = 0x047CB9;
  constexpr uint24_t Bid_Numbers = 0x047D93;
  constexpr uint24_t Bid_Top = 0x047E67;
  constexpr uint24_t Bid_Bottom = 0x048E95;
  constexpr uint24_t Bid_Left = 0x049EC3;
  constexpr uint24_t Bid_Right = 0x04A03F;
  constexpr uint24_t Bid_Top_Discard = 0x04A1BB;
  constexpr uint24_t Bid_Bottom_Discard = 0x04A25F;
  constexpr uint24_t Bid_Left_Discard = 0x04A303;
  constexpr uint24_t Bid_Right_Discard = 0x04A3AD;
  constexpr uint24_t Bid_Result = 0x04A457;
  constexpr uint24_t Bid_Result_Narrow = 0x04B101;
  constexpr uint24_t TitleEuchre = 0x04B7A8;
  constexpr uint24_t TitleEuchre_Assist = 0x0637AA;
  constexpr uint24_t Dealer = 0x0643AC;
  constexpr uint24_t EveryonePassed = 0x0643BD;
  constexpr uint24_t KittyInstructions = 0x06449D;
  constexpr uint24_t ChooseSuit = 0x0646D6;
  constexpr uint24_t You_Won = 0x064DBC;
  constexpr uint24_t You_Lost = 0x06F67E;
}

