#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf8c2;
constexpr uint24_t FX_DATA_BYTES = 470490;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t Cards_Bottom = 0x018810;
  constexpr uint24_t Cards_Bottom_Grey = 0x01CDAE;
  constexpr uint24_t Cards_Left = 0x02134C;
  constexpr uint24_t Cards_Right = 0x026C40;
  constexpr uint24_t Hand_Left = 0x02C534;
  constexpr uint24_t Hand_Right = 0x02CBA8;
  constexpr uint24_t Hand_Top = 0x02D21C;
  constexpr uint24_t Suit = 0x02DD34;
  constexpr uint24_t HUD_Top = 0x02DE86;
  constexpr uint24_t HUD_Bottom = 0x02EDA0;
  constexpr uint24_t Numbers_3x5 = 0x030446;
  constexpr uint24_t HUD_Trick_Score = 0x0331FC;
  constexpr uint24_t HUD_Game_Score = 0x0333B7;
  constexpr uint24_t Hand_Full = 0x035489;
  constexpr uint24_t Hand_Full_Grey = 0x035524;
  constexpr uint24_t Rotate = 0x0355BF;
  constexpr uint24_t Flip = 0x03BB01;
  constexpr uint24_t Bid_Round1 = 0x03CD03;
  constexpr uint24_t Bid_Round2 = 0x03D467;
  constexpr uint24_t Bid_Suits = 0x03E1E9;
  constexpr uint24_t Bid_Numbers = 0x03E2C3;
  constexpr uint24_t Bid_Top = 0x03E397;
  constexpr uint24_t Bid_Bottom = 0x03F3C5;
  constexpr uint24_t Bid_Left = 0x0403F3;
  constexpr uint24_t Bid_Right = 0x04056F;
  constexpr uint24_t Bid_Top_Discard = 0x0406EB;
  constexpr uint24_t Bid_Bottom_Discard = 0x04078F;
  constexpr uint24_t Bid_Left_Discard = 0x040833;
  constexpr uint24_t Bid_Right_Discard = 0x0408DD;
  constexpr uint24_t Bid_Result = 0x040987;
  constexpr uint24_t TitleEuchre = 0x041631;
  constexpr uint24_t TitleEuchre_Assist = 0x059633;
  constexpr uint24_t Dealer = 0x05A235;
  constexpr uint24_t EveryonePassed = 0x05A255;
  constexpr uint24_t KittyInstructions = 0x05A335;
  constexpr uint24_t ChooseSuit = 0x05A56E;
  constexpr uint24_t PPOT = 0x05AC54;
  constexpr uint24_t You_Won = 0x05DC56;
  constexpr uint24_t You_Lost = 0x068518;
}

